name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      VERBOSE: 1
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: make build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      VERBOSE: 1
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint
        run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      VERBOSE: 1
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        run: make test

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t ghcr.io/${GITHUB_REPOSITORY}/${{ github.event.repository.name }}:${GITHUB_SHA:0:7} .

#      - name: Tag image
#        run: docker tag ghcr.io/${GITHUB_REPOSITORY}/${{ github.event.repository.name }}:${GITHUB_SHA:0:7} ghcr.io/${GITHUB_REPOSITORY}/${{ github.event.repository.name }}:${GITHUB_REF#"refs/heads/"}
#        if: github.event_name == 'push'
#
#      - name: Tag latest image
#        run: docker tag ghcr.io/${GITHUB_REPOSITORY}/${{ github.event.repository.name }}:${GITHUB_SHA:0:7} ghcr.io/${GITHUB_REPOSITORY}/${{ github.event.repository.name }}:latest
#        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
#
#      - name: Log in to registry
#        run: echo ${{ secrets.DOCKER_GITHUB_PASSWORD }} | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin 
#        if: github.event_name == 'push'
#
#      - name: Push image
#        run: docker push ghcr.io/${GITHUB_REPOSITORY}/${{ github.event.repository.name }}
#        if: github.event_name == 'push'
